In [40]:
import os
import time
import numpy as np
import pandas as pd
import audb
import audiofile
import opensmile
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [2]:
smile = opensmile.Smile(feature_set=opensmile.FeatureSet.eGeMAPSv02, feature_level=opensmile.FeatureLevel.Functionals, num_workers=os.cpu_count()-1)
smile.feature_names

['F0semitoneFrom27.5Hz_sma3nz_amean',
 'F0semitoneFrom27.5Hz_sma3nz_stddevNorm',
 'F0semitoneFrom27.5Hz_sma3nz_percentile20.0',
 'F0semitoneFrom27.5Hz_sma3nz_percentile50.0',
 'F0semitoneFrom27.5Hz_sma3nz_percentile80.0',
 'F0semitoneFrom27.5Hz_sma3nz_pctlrange0-2',
 'F0semitoneFrom27.5Hz_sma3nz_meanRisingSlope',
 'F0semitoneFrom27.5Hz_sma3nz_stddevRisingSlope',
 'F0semitoneFrom27.5Hz_sma3nz_meanFallingSlope',
 'F0semitoneFrom27.5Hz_sma3nz_stddevFallingSlope',
 'loudness_sma3_amean',
 'loudness_sma3_stddevNorm',
 'loudness_sma3_percentile20.0',
 'loudness_sma3_percentile50.0',
 'loudness_sma3_percentile80.0',
 'loudness_sma3_pctlrange0-2',
 'loudness_sma3_meanRisingSlope',
 'loudness_sma3_stddevRisingSlope',
 'loudness_sma3_meanFallingSlope',
 'loudness_sma3_stddevFallingSlope',
 'spectralFlux_sma3_amean',
 'spectralFlux_sma3_stddevNorm',
 'mfcc1_sma3_amean',
 'mfcc1_sma3_stddevNorm',
 'mfcc2_sma3_amean',
 'mfcc2_sma3_stddevNorm',
 'mfcc3_sma3_amean',
 'mfcc3_sma3_stddevNorm',
 'mfcc4_

In [3]:
data_dir = os.path.join('data\\AudioData')
file_list = os.listdir(data_dir)
all_files = []
for i in file_list:
    file_list_path = os.path.join(data_dir,i)
    file_paths = [os.path.join(file_list_path,j) for j in os.listdir(file_list_path)]
    all_files.extend(file_paths)
    # print(os.path.join(data_dir,i,j) for j in file_names)
    # all_files.append(file_name for file_name in file_names)
print(all_files)

['data\\AudioData\\DC\\a01.wav', 'data\\AudioData\\DC\\a02.wav', 'data\\AudioData\\DC\\a03.wav', 'data\\AudioData\\DC\\a04.wav', 'data\\AudioData\\DC\\a05.wav', 'data\\AudioData\\DC\\a06.wav', 'data\\AudioData\\DC\\a07.wav', 'data\\AudioData\\DC\\a08.wav', 'data\\AudioData\\DC\\a09.wav', 'data\\AudioData\\DC\\a10.wav', 'data\\AudioData\\DC\\a11.wav', 'data\\AudioData\\DC\\a12.wav', 'data\\AudioData\\DC\\a13.wav', 'data\\AudioData\\DC\\a14.wav', 'data\\AudioData\\DC\\a15.wav', 'data\\AudioData\\DC\\d01.wav', 'data\\AudioData\\DC\\d02.wav', 'data\\AudioData\\DC\\d03.wav', 'data\\AudioData\\DC\\d04.wav', 'data\\AudioData\\DC\\d05.wav', 'data\\AudioData\\DC\\d06.wav', 'data\\AudioData\\DC\\d07.wav', 'data\\AudioData\\DC\\d08.wav', 'data\\AudioData\\DC\\d09.wav', 'data\\AudioData\\DC\\d10.wav', 'data\\AudioData\\DC\\d11.wav', 'data\\AudioData\\DC\\d12.wav', 'data\\AudioData\\DC\\d13.wav', 'data\\AudioData\\DC\\d14.wav', 'data\\AudioData\\DC\\d15.wav', 'data\\AudioData\\DC\\f01.wav', 'data\\

In [4]:
df=smile.process_files(all_files)

In [5]:
df

F0semitoneFrom27.5Hz_sma3nz_amean  \
file                       start  end                                                            
data\AudioData\DC\a01.wav  0 days 0 days 00:00:03.647800454                          32.288380   
data\AudioData\DC\a02.wav  0 days 0 days 00:00:03.438140590                          28.624493   
data\AudioData\DC\a03.wav  0 days 0 days 00:00:02.075487528                          32.756123   
data\AudioData\DC\a04.wav  0 days 0 days 00:00:02.725351474                          30.764029   
data\AudioData\DC\a05.wav  0 days 0 days 00:00:02.997913832                          32.762291   
...                                                                                        ...   
data\AudioData\KL\su11.wav 0 days 0 days 00:00:02.014058957                          27.108356   
data\AudioData\KL\su12.wav 0 days 0 days 00:00:03.904240363                          29.356764   
data\AudioData\KL\su13.wav 0 days 0 days 00:00:03.532380952                          29.011465   
data\AudioData\KL\su14.wav 0 days 0 days 00:00:05.267619048                          28.444342   
data\AudioData\KL\su15.wav 0 days 0 days 00:00:05.856326531                          28.733866   

                                                             F0semitoneFrom27.5Hz_sma3nz_stddevNorm  \
file                       start  end                                                                 
data\AudioData\DC\a01.wav  0 days 0 days 00:00:03.647800454                                0.253543   
data\AudioData\DC\a02.wav  0 days 0 days 00:00:03.438140590                                0.083322   
data\AudioData\DC\a03.wav  0 days 0 days 00:00:02.075487528                                0.073900   
data\AudioData\DC\a04.wav  0 days 0 days 00:00:02.725351474                                0.126925   
data\AudioData\DC\a05.wav  0 days 0 days 00:00:02.997913832                                0.264996   
...                                                                                             ...   
data\AudioData\KL\su11.wav 0 days 0 days 00:00:02.014058957                                0.206385   
data\AudioData\KL\su12.wav 0 days 0 days 00:00:03.904240363                                0.251457   
data\AudioData\KL\su13.wav 0 days 0 days 00:00:03.532380952                                0.158787   
data\AudioData\KL\su14.wav 0 days 0 days 00:00:05.267619048                                0.174112   
data\AudioData\KL\su15.wav 0 days 0 days 00:00:05.856326531                                0.171200   

                                                             F0semitoneFrom27.5Hz_sma3nz_percentile20.0  \
file                       start  end                                                                     
data\AudioData\DC\a01.wav  0 days 0 days 00:00:03.647800454                                   28.019901   
data\AudioData\DC\a02.wav  0 days 0 days 00:00:03.438140590                                   27.068924   
data\AudioData\DC\a03.wav  0 days 0 days 00:00:02.075487528                                   30.584627   
data\AudioData\DC\a04.wav  0 days 0 days 00:00:02.725351474                                   28.082645   
data\AudioData\DC\a05.wav  0 days 0 days 00:00:02.997913832                                   28.170227   
...                                                                                                 ...   
data\AudioData\KL\su11.wav 0 days 0 days 00:00:02.014058957                                   20.513931   
data\AudioData\KL\su12.wav 0 days 0 days 00:00:03.904240363                                   24.306232   
data\AudioData\KL\su13.wav 0 days 0 days 00:00:03.532380952                                   25.771935   
data\AudioData\KL\su14.wav 0 days 0 days 00:00:05.267619048                                   24.197414   
data\AudioData\KL\su15.wav 0 days 0 days 00:00:05.856326531                                   25.216961   

                                                      

In [6]:
df.to_csv(path_or_buf='dataset.csv')

In [41]:
data = pd.read_csv('dataset.csv')

In [42]:
def get_file_emotion(file_path):
    # file_path = "data\\AudioData\\KL\\n17.wav"
    file_parts = file_path.split("\\")
    file_name = file_parts[-1]
    file_name = file_name.split('.')[0]
    # print(file_name)
    if 'a' in file_name:
        if 'sa' in file_name:
            return 'sadness'
        return 'anger'
    elif 'd' in file_name:
        return 'disgust'
    elif 'f' in file_name:
        return 'fear'
    elif 'h' in file_name:
        return 'happiness'
    elif 'n' in file_name:
        return 'neutral'
    else:
        return 'surprise'

In [43]:
data['emotion'] = data['file'].apply(get_file_emotion)
data

file   start                        end  \
0     data\AudioData\DC\a01.wav  0 days  0 days 00:00:03.647800454   
1     data\AudioData\DC\a02.wav  0 days  0 days 00:00:03.438140590   
2     data\AudioData\DC\a03.wav  0 days  0 days 00:00:02.075487528   
3     data\AudioData\DC\a04.wav  0 days  0 days 00:00:02.725351474   
4     data\AudioData\DC\a05.wav  0 days  0 days 00:00:02.997913832   
..                          ...     ...                        ...   
475  data\AudioData\KL\su11.wav  0 days  0 days 00:00:02.014058957   
476  data\AudioData\KL\su12.wav  0 days  0 days 00:00:03.904240363   
477  data\AudioData\KL\su13.wav  0 days  0 days 00:00:03.532380952   
478  data\AudioData\KL\su14.wav  0 days  0 days 00:00:05.267619048   
479  data\AudioData\KL\su15.wav  0 days  0 days 00:00:05.856326531   

     F0semitoneFrom27.5Hz_sma3nz_amean  \
0                            32.288380   
1                            28.624493   
2                            32.756123   
3                            30.764029   
4                            32.762290   
..                                 ...   
475                          27.108356   
476                          29.356764   
477                          29.011465   
478                          28.444342   
479                          28.733866   

     F0semitoneFrom27.5Hz_sma3nz_stddevNorm  \
0                                  0.253543   
1                                  0.083322   
2                                  0.073900   
3                                  0.126925   
4                                  0.264996   
..                                      ...   
475                                0.206385   
476                                0.251457   
477                                0.158787   
478                                0.174112   
479                                0.171200   

     F0semitoneFrom27.5Hz_sma3nz_percentile20.0  \
0                                     28.019901   
1                                     27.068924   
2                                     30.584627   
3                                     28.082645   
4                                     28.170227   
..                                          ...   
475                                   20.513931   
476                                   24.306232   
477                                   25.771935   
478                                   24.197414   
479                                   25.216960   

     F0semitoneFrom27.5Hz_sma3nz_percentile50.0  \
0                                     31.009487   
1                                     28.368698   
2                                     33.153530   
3                                     31.094270   
4                                     30.551092   
..                                          ...   
475                                   27.355310   
476                                   27.609499   
477                                   29.877594   
478                                   28.833923   
479                                   29.166946   

     F0semitoneFrom27.5Hz_sma3nz_percentile80.0  \
0                                     34.035740   
1                                     29.564380   
2                                     34.469784   
3                                     33.430504   
4                                     34.771940   
..                                          ...   
475                                   32.252160   
476                                   33.923820   
477                                   32.168106   
478                                   32.693604   
479                                   32.431194   

     F0semitoneFrom27.5Hz_sma3nz_pctlrange0-2  \
0                                    6.015839   
1                                    2.495457   
2                                    3.885157   
3                                    5.347858   
4                               

In [44]:
data = data.drop(['file', 'start', 'end'], axis='columns')
data

F0semitoneFrom27.5Hz_sma3nz_amean  \
0                            32.288380   
1                            28.624493   
2                            32.756123   
3                            30.764029   
4                            32.762290   
..                                 ...   
475                          27.108356   
476                          29.356764   
477                          29.011465   
478                          28.444342   
479                          28.733866   

     F0semitoneFrom27.5Hz_sma3nz_stddevNorm  \
0                                  0.253543   
1                                  0.083322   
2                                  0.073900   
3                                  0.126925   
4                                  0.264996   
..                                      ...   
475                                0.206385   
476                                0.251457   
477                                0.158787   
478                                0.174112   
479                                0.171200   

     F0semitoneFrom27.5Hz_sma3nz_percentile20.0  \
0                                     28.019901   
1                                     27.068924   
2                                     30.584627   
3                                     28.082645   
4                                     28.170227   
..                                          ...   
475                                   20.513931   
476                                   24.306232   
477                                   25.771935   
478                                   24.197414   
479                                   25.216960   

     F0semitoneFrom27.5Hz_sma3nz_percentile50.0  \
0                                     31.009487   
1                                     28.368698   
2                                     33.153530   
3                                     31.094270   
4                                     30.551092   
..                                          ...   
475                                   27.355310   
476                                   27.609499   
477                                   29.877594   
478                                   28.833923   
479                                   29.166946   

     F0semitoneFrom27.5Hz_sma3nz_percentile80.0  \
0                                     34.035740   
1                                     29.564380   
2                                     34.469784   
3                                     33.430504   
4                                     34.771940   
..                                          ...   
475                                   32.252160   
476                                   33.923820   
477                                   32.168106   
478                                   32.693604   
479                                   32.431194   

     F0semitoneFrom27.5Hz_sma3nz_pctlrange0-2  \
0                                    6.015839   
1                                    2.495457   
2                                    3.885157   
3                                    5.347858   
4                                    6.601711   
..                                        ...   
475                                 11.738228   
476                                  9.617588   
477                                  6.396172   
478                                  8.496189   
479                                  7.214233   

     F0semitoneFrom27.5Hz_sma3nz_meanRisingSlope  \
0                                     630.634460   
1                                     162.988590   
2                                      89.154755   
3                                     199.326310   
4                                     991.748170   
..                                           ...   
475                                   345.076200   
476                                   194.198040   
477                                   4

In [45]:
Y = data['emotion'].to_frame()
Y

emotion
0       anger
1       anger
2       anger
3       anger
4       anger
..        ...
475  surprise
476  surprise
477  surprise
478  surprise
479  surprise

[480 rows x 1 columns]

In [46]:
X = data.drop(columns=['emotion'])

In [47]:
norm = MinMaxScaler(feature_range=(-1, 1))
X_norm = norm.fit_transform(X)
X_norm

array([[ 0.02661411,  0.34893161, -0.10823616, ..., -0.15428576,
        -0.01526576,  0.57124526],
       [-0.40808994, -0.65724805, -0.20539704, ...,  0.2       ,
         0.21490972,  0.5583704 ],
       [ 0.08210975, -0.71293781,  0.15380071, ...,  0.19238089,
        -0.10575111,  0.66061364],
       ...,
       [-0.36217742, -0.21117025, -0.33790981, ..., -0.54775515,
        -0.33581442, -0.56032195],
       [-0.42946407, -0.12058368, -0.4987779 , ..., -0.52761902,
        -0.27205796, -0.55682812],
       [-0.39511332, -0.137798  , -0.39461135, ..., -0.68857143,
        -0.33401451, -0.5647845 ]])

In [48]:
Y

emotion
0       anger
1       anger
2       anger
3       anger
4       anger
..        ...
475  surprise
476  surprise
477  surprise
478  surprise
479  surprise

[480 rows x 1 columns]

Feature Selection

In [49]:
from sklearn.feature_selection import mutual_info_classif

In [50]:
threshold = 5
high_score_feats = []
y = np.ravel(Y.values)
feature_scores = mutual_info_classif(X_norm, y)

In [51]:
feature_scores

array([0.54977807, 0.0821471 , 0.359195  , 0.56874873, 0.59494752,
       0.29488303, 0.04510264, 0.02219064, 0.03044852, 0.08354473,
       0.50747649, 0.0099042 , 0.09513092, 0.32079027, 0.54401643,
       0.4964338 , 0.39116972, 0.23187165, 0.47027408, 0.25159295,
       0.65027008, 0.06154577, 0.12294628, 0.10570109, 0.06439916,
       0.134461  , 0.17500497, 0.21261711, 0.21434074, 0.12546625,
       0.        , 0.03966662, 0.03160857, 0.        , 0.21919008,
       0.11153381, 0.20834152, 0.05800228, 0.12051358, 0.04357731,
       0.04353678, 0.00216669, 0.02609269, 0.03574628, 0.11753309,
       0.06389328, 0.06320035, 0.00408108, 0.05054339, 0.02721742,
       0.09197442, 0.05703708, 0.02186584, 0.        , 0.07979289,
       0.02071997, 0.13138017, 0.17638343, 0.21173535, 0.16164715,
       0.26566233, 0.14463986, 0.40263582, 0.33998383, 0.05923742,
       0.        , 0.64133354, 0.07640054, 0.22881945, 0.09286086,
       0.0596664 , 0.1062826 , 0.16792048, 0.15225468, 0.06192

In [52]:
for score, f_name in sorted(zip(feature_scores, X.columns), reverse=True):
        print(f_name, score)
        if score > 0.0:
                high_score_feats.append(f_name)

spectralFlux_sma3_amean 0.6502700814356559
equivalentSoundLevel_dBp 0.6450074763265028
spectralFluxV_sma3nz_amean 0.6413335402287585
F0semitoneFrom27.5Hz_sma3nz_percentile80.0 0.594947515581457
F0semitoneFrom27.5Hz_sma3nz_percentile50.0 0.5687487322806546
F0semitoneFrom27.5Hz_sma3nz_amean 0.5497780670720802
loudness_sma3_percentile80.0 0.5440164296380097
loudness_sma3_amean 0.5074764877435483
loudness_sma3_pctlrange0-2 0.49643380403033044
loudness_sma3_meanFallingSlope 0.4702740829981229
slopeV0-500_sma3nz_amean 0.40263581730732456
loudness_sma3_meanRisingSlope 0.39116972347483525
F0semitoneFrom27.5Hz_sma3nz_percentile20.0 0.3591950026416124
slopeV0-500_sma3nz_stddevNorm 0.3399838271737772
loudness_sma3_percentile50.0 0.3207902697219138
F0semitoneFrom27.5Hz_sma3nz_pctlrange0-2 0.29488302668969224
hammarbergIndexV_sma3nz_amean 0.2656623343753015
loudness_sma3_stddevFallingSlope 0.2515929491609299
loudness_sma3_stddevRisingSlope 0.23187165346654348
mfcc1V_sma3nz_amean 0.22881945186214114

In [53]:
high_score_feats

['spectralFlux_sma3_amean',
 'equivalentSoundLevel_dBp',
 'spectralFluxV_sma3nz_amean',
 'F0semitoneFrom27.5Hz_sma3nz_percentile80.0',
 'F0semitoneFrom27.5Hz_sma3nz_percentile50.0',
 'F0semitoneFrom27.5Hz_sma3nz_amean',
 'loudness_sma3_percentile80.0',
 'loudness_sma3_amean',
 'loudness_sma3_pctlrange0-2',
 'loudness_sma3_meanFallingSlope',
 'slopeV0-500_sma3nz_amean',
 'loudness_sma3_meanRisingSlope',
 'F0semitoneFrom27.5Hz_sma3nz_percentile20.0',
 'slopeV0-500_sma3nz_stddevNorm',
 'loudness_sma3_percentile50.0',
 'F0semitoneFrom27.5Hz_sma3nz_pctlrange0-2',
 'hammarbergIndexV_sma3nz_amean',
 'loudness_sma3_stddevFallingSlope',
 'loudness_sma3_stddevRisingSlope',
 'mfcc1V_sma3nz_amean',
 'HNRdBACF_sma3nz_amean',
 'mfcc4_sma3_amean',
 'mfcc3_sma3_stddevNorm',
 'alphaRatioV_sma3nz_amean',
 'logRelF0-H1-H2_sma3nz_amean',
 'F3amplitudeLogRelF0_sma3nz_stddevNorm',
 'mfcc3_sma3_amean',
 'mfcc3V_sma3nz_amean',
 'alphaRatioV_sma3nz_stddevNorm',
 'spectralFluxUV_sma3nz_amean',
 'mfcc3V_sma3nz_s

In [54]:
X_norm_df = pd.DataFrame(X_norm, columns=X.columns)

In [55]:
data_mic = X_norm_df[high_score_feats]

In [56]:
print(data_mic)

     spectralFlux_sma3_amean  equivalentSoundLevel_dBp  \
0                  -0.304646                  0.571245   
1                  -0.307531                  0.558370   
2                  -0.243889                  0.660614   
3                  -0.197784                  0.708982   
4                  -0.284873                  0.700610   
..                       ...                       ...   
475                -0.969772                 -0.606334   
476                -0.963349                 -0.620018   
477                -0.963761                 -0.560322   
478                -0.959233                 -0.556828   
479                -0.956280                 -0.564785   

     spectralFluxV_sma3nz_amean  F0semitoneFrom27.5Hz_sma3nz_percentile80.0  \
0                     -0.288724                                   -0.248995   
1                     -0.192504                                   -0.628796   
2                      0.077646                                   

In [57]:
Y = pd.get_dummies(Y)
Y

emotion_anger  emotion_disgust  emotion_fear  emotion_happiness  \
0                1                0             0                  0   
1                1                0             0                  0   
2                1                0             0                  0   
3                1                0             0                  0   
4                1                0             0                  0   
..             ...              ...           ...                ...   
475              0                0             0                  0   
476              0                0             0                  0   
477              0                0             0                  0   
478              0                0             0                  0   
479              0                0             0                  0   

     emotion_neutral  emotion_sadness  emotion_surprise  
0                  0                0                 0  
1                  0                0                 0  
2                  0                0                 0  
3                  0                0                 0  
4                  0                0                 0  
..               ...              ...               ...  
475                0                0                 1  
476                0                0                 1  
477                0                0                 1  
478                0                0                 1  
479                0                0                 1  

[480 rows x 7 columns]

In [19]:
removed_feats = []
with open('removed features.txt') as f:
    removed_feats = f.read().splitlines()
removed_feats

['slopeUV0-500_sma3nz_amean',
 'loudness_sma3_percentile20.0',
 'mfcc1V_sma3nz_stddevNorm',
 'F2amplitudeLogRelF0_sma3nz_amean',
 'F0semitoneFrom27.5Hz_sma3nz_stddevFallingSlope',
 'F0semitoneFrom27.5Hz_sma3nz_stddevNorm',
 'F3bandwidth_sma3nz_amean',
 'spectralFluxV_sma3nz_stddevNorm',
 'MeanVoicedSegmentLengthSec',
 'mfcc2_sma3_amean',
 'F1amplitudeLogRelF0_sma3nz_stddevNorm',
 'F2frequency_sma3nz_amean',
 'mfcc4V_sma3nz_amean',
 'spectralFlux_sma3_stddevNorm',
 'slopeV500-1500_sma3nz_amean',
 'mfcc2V_sma3nz_amean',
 'logRelF0-H1-H2_sma3nz_stddevNorm',
 'F2amplitudeLogRelF0_sma3nz_stddevNorm',
 'StddevVoicedSegmentLengthSec',
 'F2bandwidth_sma3nz_amean',
 'MeanUnvoicedSegmentLength',
 'F0semitoneFrom27.5Hz_sma3nz_meanRisingSlope',
 'logRelF0-H1-A3_sma3nz_stddevNorm',
 'F1frequency_sma3nz_amean',
 'jitterLocal_sma3nz_stddevNorm',
 'F1bandwidth_sma3nz_stddevNorm',
 'shimmerLocaldB_sma3nz_amean',
 'F0semitoneFrom27.5Hz_sma3nz_meanFallingSlope',
 'F2bandwidth_sma3nz_stddevNorm',
 'F1band

In [20]:
X_norm_df_mic = X_norm_df.drop(columns=removed_feats)
X_norm_df_mic

F0semitoneFrom27.5Hz_sma3nz_amean  \
0                             0.026614   
1                            -0.408090   
2                             0.082110   
3                            -0.154243   
4                             0.082841   
..                                 ...   
475                          -0.587973   
476                          -0.321209   
477                          -0.362177   
478                          -0.429464   
479                          -0.395113   

     F0semitoneFrom27.5Hz_sma3nz_percentile20.0  \
0                                     -0.108236   
1                                     -0.205397   
2                                      0.153801   
3                                     -0.101826   
4                                     -0.092877   
..                                          ...   
475                                   -0.875118   
476                                   -0.487660   
477                                   -0.337910   
478                                   -0.498778   
479                                   -0.394611   

     F0semitoneFrom27.5Hz_sma3nz_percentile50.0  \
0                                     -0.195960   
1                                     -0.458080   
2                                      0.016853   
3                                     -0.187545   
4                                     -0.241460   
..                                          ...   
475                                   -0.558666   
476                                   -0.533436   
477                                   -0.308310   
478                                   -0.411902   
479                                   -0.378847   

     F0semitoneFrom27.5Hz_sma3nz_percentile80.0  \
0                                     -0.248995   
1                                     -0.628796   
2                                     -0.212127   
3                                     -0.300404   
4                                     -0.186461   
..                                          ...   
475                                   -0.400493   
476                                   -0.258501   
477                                   -0.407633   
478                                   -0.362997   
479                                   -0.385286   

     F0semitoneFrom27.5Hz_sma3nz_pctlrange0-2  loudness_sma3_amean  \
0                                   -0.628393            -0.276664   
1                                   -0.910681            -0.101197   
2                                   -0.799245            -0.129086   
3                                   -0.681956            -0.150283   
4                                   -0.581414            -0.061027   
..                                        ...                  ...   
475                                 -0.169533            -0.958673   
476                                 -0.339580            -0.950685   
477                                 -0.597895            -0.951143   
478                                 -0.429502            -0.943536   
479                                 -0.532298            -0.933991   

     loudness_sma3_percentile50.0  loudness_sma3_percentile80.0  \
0                       -0.156963                     -0.379474   
1                       -0.104713                     -0.117545   
2                       -0.726114                     -0.199666   
3                       -0.359487                     -0.143678   
4                       -0.272436                     -0.066554   
..                            ...                           ...   
475                     -0.902185                     -0.966814   
476                     -0.903453                     -0.956986   
477                     -0.915724                     -0.954033   
478                     -0.927813                     -0.942073   
479                     -0.903082                     -0.934039   

     loudness_s

In [58]:
X_train, X_test, y_train, y_test = train_test_split(data_mic, Y, test_size=0.2, random_state=27)

In [59]:
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [61]:
knn.score(X_train, y_train)

0.7265625

In [62]:
knn.score(X_test, y_test)

0.5729166666666666

In [63]:
y_pred = knn.predict(X_test)

In [64]:
print(y_test)

     emotion_anger  emotion_disgust  emotion_fear  emotion_happiness  \
249              1                0             0                  0   
453              0                0             0                  0   
195              0                0             0                  0   
383              0                1             0                  0   
223              0                0             0                  0   
..             ...              ...           ...                ...   
372              1                0             0                  0   
208              0                0             0                  0   
77               0                0             0                  0   
206              0                0             0                  0   
311              0                0             0                  0   

     emotion_neutral  emotion_sadness  emotion_surprise  
249                0                0                 0  
453                

In [65]:
print(confusion_matrix(y_test.values.argmax(axis=1), y_pred.argmax(axis=1)))

[[15  0  0  1  0  0  0]
 [ 6  5  0  0  5  0  0]
 [ 5  0  4  0  0  0  2]
 [ 3  0  0  4  0  0  2]
 [ 4  0  0  0 17  0  0]
 [ 0  0  0  0  3  8  0]
 [ 3  0  0  3  0  0  6]]


In [28]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.85      0.69      0.76        16
           1       1.00      0.31      0.48        16
           2       1.00      0.36      0.53        11
           3       0.50      0.44      0.47         9
           4       0.68      0.81      0.74        21
           5       1.00      0.73      0.84        11
           6       0.60      0.50      0.55        12

   micro avg       0.75      0.57      0.65        96
   macro avg       0.80      0.55      0.62        96
weighted avg       0.81      0.57      0.64        96
 samples avg       0.57      0.57      0.57        96



f:\Virang ka Kaam\Automated-EQ\env\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [29]:
print(y_pred)

[[1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0]
 [1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1]
 [0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1]
 [0 0 0 0 1 0 0]
 [0 0 0 1 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 1 0 

In [113]:
from sklearn.model_selection import cross_val_score

In [114]:
knn_cv = KNeighborsClassifier(n_neighbors=3)

In [115]:
cv_scores = cross_val_score(knn_cv, data_mic, Y, cv=5)

In [116]:
cv_scores1 = cross_val_score(knn_cv, X_train, y_train, cv=5)

In [119]:
print(cv_scores1)
print('cv_scores1 mean:{}'.format(np.mean(cv_scores1)))

[0.44155844 0.48051948 0.50649351 0.53246753 0.57894737]
cv_scores1 mean:0.5079972658920027


In [117]:
print(cv_scores)
print('cv_scores mean:{}'.format(np.mean(cv_scores)))

[0.35416667 0.26041667 0.30208333 0.08333333 0.05208333]
cv_scores mean:0.21041666666666664


In [118]:
print(cv_scores1)
print('cv_scores1 mean:{}'.format(np.mean(cv_scores1)))

[0.44155844 0.48051948 0.50649351 0.53246753 0.57894737]
cv_scores1 mean:0.5079972658920027


Hyperparameter tuning and optimization

In [105]:
knn_hyper = KNeighborsClassifier()
param_grid = { 'n_neighbors' : [4,5,6,7,8,9,10,11,12,13,14,15],
               'weights' : ['uniform','distance'],
               'metric' : ['minkowski','euclidean','manhattan']}

In [106]:
from sklearn.model_selection import GridSearchCV

In [107]:
gscv = GridSearchCV(knn_hyper, param_grid, verbose = 1, cv=3, n_jobs=-1)
gscv.fit(X_train, y_train)

Fitting 3 folds for each of 72 candidates, totalling 216 fits


GridSearchCV(cv=3, estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'metric': ['minkowski', 'euclidean', 'manhattan'],
                         'n_neighbors': [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14,
                                         15],
                         'weights': ['uniform', 'distance']},
             verbose=1)

In [108]:
gscv.best_params_

{'metric': 'manhattan', 'n_neighbors': 4, 'weights': 'distance'}

In [109]:
gscv.best_score_

0.53125

In [110]:
knn_gscv = KNeighborsClassifier(n_neighbors=5, weights='uniform', algorithm='brute', metric='manhattan')
knn_gscv.fit(X_train, y_train)

KNeighborsClassifier(algorithm='brute', metric='manhattan')

In [111]:
knn_gscv.score(X_train, y_train)

0.6588541666666666

In [112]:
knn_gscv.score(X_test, y_test)

0.5104166666666666